spring.application.name=api-gateway

# Puerto del Gateway
server.port=8080

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Usuarios
spring.cloud.gateway.routes[0].id=usuarios-service
spring.cloud.gateway.routes[0].uri=lb://usuarios-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/usuarios/**

# Peliculas
spring.cloud.gateway.routes[1].id=pelicula-service
spring.cloud.gateway.routes[1].uri=lb://pelicula-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/peliculas/**

# Calificaciones
spring.cloud.gateway.routes[2].id=calificacion-service
spring.cloud.gateway.routes[2].uri=lb://calificacion-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/calificaciones/**

# Directores
spring.cloud.gateway.routes[3].id=director-service
spring.cloud.gateway.routes[3].uri=lb://director-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/directores/**

# Mi Lista
spring.cloud.gateway.routes[4].id=mi-lista-service
spring.cloud.gateway.routes[4].uri=lb://mi-lista-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/mi-lista/**

# Productora
spring.cloud.gateway.routes[5].id=productora-service
spring.cloud.gateway.routes[5].uri=lb://productora-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/productoras/**

# Recomendaciones
spring.cloud.gateway.routes[6].id=recomendacion-service
spring.cloud.gateway.routes[6].uri=lb://recomendacion-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/recomendaciones/**

# Suscripciones
spring.cloud.gateway.routes[7].id=suscripciones-service
spring.cloud.gateway.routes[7].uri=lb://suscripciones-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/suscripciones/**
