spring.application.name=calificacion-service
server.port=0

spring.output.ansi.enabled=always

#conectar a eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true

# Configuración de la DB
spring.datasource.url=jdbc:mariadb://localhost:3306/calificacion_service
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=false
