spring.application.name=eureka-server
# El puerto estándar para Eureka es el 8761
server.port=8761

# Estas dos líneas evitan el error de "DiscoveryClient" al arrancar
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuración opcional para mejorar la estabilidad en local
eureka.instance.hostname=localhost

spring.output.ansi.enabled=ALWAYS